### ISSUE TITLE
Enable nitro to run in monorepo environment

### ISSUE THREAD

**Issue by ernscht** [namics/generator-nitro#126]
Try to identify what is necessary to setiup and run a nitro project in a monorepo with lerna
* [x] support for cli options of all configuration parameters #128
* [x] support for hoisted dependencies #125 
* [x] what to do with current githooks implementation -> #132
* [x] what dependencies exist and how to handle between root of monorepo and nitro project (node and npm version, linting, ...) -> maybe try to use local node version?
* ...

**Comment by ernscht** [comment]
Works since 3.5
More will be covered in [v4](../milestone/9)
